/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCog,
  faInfinity,
  faHistory,
  faBullseye,
  faMedal,
  faChevronRight,
  faMousePointer,
  faFileDownload,
  faTrash,
  faExchangeAlt,
  faSignOut,
  faArrowDown,
  faAt,
  faKey,
  faExclamationTriangle,
  faTimes,
  faSignature,
  faUser,
  faCloud,
  faSort,
  faThermometerEmpty,
  faThermometerFull,
  faSitemap,
  faSortUp,
  faSortDown,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faCog,
  faInfinity,
  faHistory,
  faBullseye,
  faMedal,
  faChevronRight,
  faMousePointer,
  faFileDownload,
  faTrash,
  faExchangeAlt,
  faSignOut,
  faArrowDown,
  faAt,
  faKey,
  faExclamationTriangle,
  faTimes,
  faSignature,
  faUser,
  faCloud,
  faSort,
  faThermometerEmpty,
  faThermometerFull,
  faSitemap,
  faSortUp,
  faSortDown
);

export default FontAwesomeIcon;
