/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCog,
  faInfinity,
  faHistory,
  faBullseye,
  faMedal,
  faChevronRight,
  faChevronLeft,
  faMousePointer,
  faFileDownload,
  faTrash,
  faExchangeAlt,
  faSignOut,
  faArrowDown,
  faAt,
  faKey,
  faExclamationTriangle,
  faTimes,
  faSignature,
  faUser,
  faCloud,
  faSort,
  faThermometerEmpty,
  faThermometerFull,
  faSitemap,
  faSortUp,
  faSortDown,
  faDraftingCompass,
  faPlus,
  faEdit,
  faLongArrowAltRight,
  faLongArrowAltLeft,
  faTape,
  faPaperPlane,
  faCamera,
  faCalendarDay,
  faCompass,
  faSmog,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faCog,
  faInfinity,
  faHistory,
  faBullseye,
  faMedal,
  faChevronRight,
  faChevronLeft,
  faMousePointer,
  faFileDownload,
  faTrash,
  faExchangeAlt,
  faSignOut,
  faArrowDown,
  faAt,
  faKey,
  faExclamationTriangle,
  faTimes,
  faSignature,
  faUser,
  faCloud,
  faSort,
  faThermometerEmpty,
  faThermometerFull,
  faSitemap,
  faSortUp,
  faSortDown,
  faDraftingCompass,
  faPlus,
  faEdit,
  faLongArrowAltRight,
  faLongArrowAltLeft,
  faTape,
  faPaperPlane,
  faCamera,
  faCalendarDay,
  faCompass,
  faSmog
);

export default FontAwesomeIcon;
